export const opstineSrbije = [
  // Beogradske opštine
  "Barajevo",
  "Voždovac",
  "Vračar",
  "Grocka",
  "Zvezdara",
  "Zemun",
  "Lazarevac",
  "Mladenovac",
  "Novi Beograd",
  "Palilula",
  "Rakovica",
  "Savski venac",
  "Sopot",
  "Stari grad",
  "Surčin",
  "Čukarica",

  // Vojvodina
  "Ada",
  "Alibunar",
  "Apatin",
  "Bač",
  "Bačka Palanka",
  "Bačka Topola",
  "Bački Petrovac",
  "Bela Crkva",
  "Beočin",
  "Bečej",
  "Vrbas",
  "Vršac",
  "Žabalj",
  "Žitište",
  "Zrenjanin",
  "Inđija",
  "Irig",
  "Kanjiža",
  "Kikinda",
  "Kovačica",
  "Kovin",
  "Kula",
  "Mali Iđoš",
  "Nikinci",
  "Nova Crnja",
  "Novi Bečej",
  "Novi Kneževac",
  "Novi Sad",
  "Opovo",
  "Pančevo",
  "Pećinci",
  "Ruma",
  "Senta",
  "Sečanj",
  "Sombor",
  "Srbobran",
  "Sremska Mitrovica",
  "Sremski Karlovci",
  "Stara Pazova",
  "Subotica",
  "Temerin",
  "Titel",
  "Čoka",
  "Šid",

  // Šumadija i Zapadna Srbija
  "Aranđelovac",
  "Arilje",
  "Bajina Bašta",
  "Batočina",
  "Despotovac",
  "Gornji Milanovac",
  "Jagodina",
  "Knić",
  "Kragujevac",
  "Kraljevo",
  "Kruševac",
  "Lapovo",
  "Lučani",
  "Čačak",
  "Paraćin",
  "Petrovac na Mlavi",
  "Požega",
  "Prijepolje",
  "Raška",
  "Rekovac",
  "Svilajnac",
  "Topola",
  "Tutin",
  "Ćuprija",
  "Užice",
  "Vrnjačka Banja",
  "Žagubica",

  // Južna i Istočna Srbija
  "Aleksinac",
  "Babušnica",
  "Bela Palanka",
  "Bor",
  "Bosilegrad",
  "Bujanovac",
  "Vlasotince",
  "Vranje",
  "Gadžin Han",
  "Dimitrovgrad",
  "Doljevac",
  "Zaječar",
  "Knjaževac",
  "Leskovac",
  "Majdanpek",
  "Medveđa",
  "Merošina",
  "Negotin",
  "Niš",
  "Niška Banja",
  "Pirot",
  "Pčinja",
  "Preševo",
  "Ražanj",
  "Sokobanja",
  "Surdulica",
  "Svrljig",
  "Trgovište",
  "Crna Trava",
  "Šabac",

  // Mačvanski, Kolubarski, Podunavski okrug
  "Bajina Bašta",
  "Vladimirci",
  "Valjevo",
  "Smederevo",
  "Smederevska Palanka",
  "Koceljeva",
  "Krupanj",
  "Ljubovija",
  "Lajkovac",
  "Ljig",
  "Mali Zvornik",
  "Mionica",
  "Osečina",
  "Ub",

  // Pomoravski, Braničevski, Zlatiborski okrug
  "Golubac",
  "Kučevo",
  "Požarevac",
  "Malo Crniće",
  "Žabari",
  "Čajetina",
  "Nova Varoš",
  "Kosjerić",
  "Ivanjica",
  "Sjenica",
] as const;

export type Opstina = (typeof opstineSrbije)[number];
